### ISSUE TITLE
Unable to log in using default credentials

### ISSUE THREAD

**Issue by rplescia** [synmetrix/synmetrix#124]
Hi team,

I'm following the documentation to pull and deploy the docker containers, which all works fine, I can see the relevant containers have started and I'm able to navigate to the login page. When trying to log in using 'demo@synmetrix.org' and 'demodemo' as credentials, nothing seems to happen apart from reloading the login page without any error or warning messages.

I have tried removing all containers and images and redeploying them with the same result.

**Comment by ifokeev** [comment]
Hi @rplescia, sorry for the late reply. It may happen only if migrations or only seeds weren't applied. 
Are you using an Apple Silicon processor? Please give more details about your setup.

**Comment by rplescia** [comment]
Hi, no problem. I'm trying to deploy it to a Cisco UCS C240 server which runs Xeon processors

**Comment by ifokeev** [comment]
@rplescia could you please provide stack logs `docker-compose logs -f`?

**Comment by rplescia** [comment]
I have found the issue, there was an SSL certificate issue which caused not all of the dependencies to pull down. Somehow the containers started 'successfully' but didn't start all the services. I've fixed the SSL issue and it now works fine.

**Comment by ifokeev** [comment]
@rplescia good job
