### ISSUE TITLE
K8s helm chart

### ISSUE THREAD

**Issue by OstapW** [synmetrix/synmetrix#127]
Hey! I'm creating a helm chart to deploy synmetrix on k8s cluster. 
Now I stuck on an issue.
I'm able to add any sample database from your sources or simple database like postgres, but when I'm trying to add AWS Redshift I get the error below on test connection:
`[GraphQL] request to http://localhost:4000/api/v1/test failed, reason: socket hang up
`
When I'm trying to make a request to the url by using curl 
`curl -v http://localhost:4000/api/v1/test`

I get the next error:
```
{"error":"Error: Provide Hasura Authorization token","stack":"Error: Provide Hasura Authorization token\n    at checkAuth (file:///app/stack/services/cubejs/src/utils/checkAuth.js:24:11)\n    at checkAuthMiddleware (file:///app/stack/services/cubejs/src/utils/checkAuth.js:89:11)\n    at Layer.handle [as handle_request] (/app/stack/services/cubejs/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/stack/services/cubejs/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/stack/services/cubejs/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/stack/services/cubejs/node_modules/express/lib/router/layer.js:95:5)\n    at /app/stack/services/cubejs/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:175:3)\n    at router (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/app/stack/services/cubejs/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:328:13)\n    at /app/stack/services/cubejs/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:280:10)\n    at urlencodedParser (/app/stack/services/cubejs/node_modules/express/node_modules/body-parser/lib/types/urlencoded.js:91:7)\n    at Layer.handle [as handle_request] (/app/stack/services/cubejs/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:328:13)\n    at /app/stack/services/cubejs/nod* Connection #0 to host localhost left intact
e_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/stack/services/cubejs/node_modules/express/lib/router/index.js:280:10)"}
```

The stack pod deployed with the next env vars:
```
            - name: AWS_S3_ACCESS_KEY_ID
            - name: AWS_S3_BUCKET_NAME
            - name: AWS_S3_SECRET_ACCESS_KEY
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: adminsecret
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://synmetrix_stack:pg_pass@postgres:5432/synmetrix_stack
            - name: SMTP_HOST
            - name: SMTP_PASS
            - name: SMTP_PORT
            - name: SMTP_SECURE
            - name: SMTP_SENDER
            - name: SMTP_USER
            - name: CUBEJS_REST_API_URL
              value: "https://synmetrix.test.domain.local/api/v1/load"
```

**Comment by ifokeev** [comment]
Hi @OstapW! I think the error is not related to the setup. All your requests to the Cube.js server should be provided with an `Authorization` header, please check https://github.com/synmetrix/synmetrix/blob/main/services/cubejs/src/utils/checkAuth.js#L44. 
Also, this might help: https://github.com/synmetrix/docs/pull/7.

**Comment by OstapW** [comment]
Hi @ifokeev
thank you for your reply!

I made an another deployment with files you provided in [PR7](https://github.com/synmetrix/docs/pull/7), but I get the same error. It looks like I should make an additional configuration to use AWS Redshift as a source, because I'm able to add another kind of sources without the error. Could you kindly help me to find it out?

**Comment by johancube** [comment]
Hi @OstapW! Could you please elaborate more on your case?

If you'd like to add the AWS Redshift datasource, you'll need to add it in the UI first https://docs.synmetrix.org/docs/user-guide/settings/data-sources, after that you'll be able to query the datasource using REST API, please check https://docs.synmetrix.org/docs/user-guide/explore#rest-api-tab.

**Comment by OstapW** [comment]
Hi @ifokeev 
I have an issue during adding my redshift as a source. 
I described all steps below

1) I have Synmetrix deployed
2) Sing in with default credentials
3) Go to Settings/Data Sources
4) Push the Create now
5) Choose Redshift
6) Fill all fields needed
7) Push Test connection and I see two alerts
first one: Data Source created
second one: [GraphQL] request to http://localhost:4000/api/v1/test failed, reason: socket hang up

In logs of statefulset stack I see next error:
`Driver error:
Error: Unexpected CreateOptions.driverFactory result value. Must be either DriverConfig or driver instance: <object>{}
    at OptsHandler.assertDriverFactoryResult (/app/stack/services/cubejs/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:153:13)
    at Object.driverFactory (/app/stack/services/cubejs/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:225:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at default (file:///app/stack/services/cubejs/src/routes/testConnection.js:14:18)
{"level":50,"time":1727343743347,"pid":330,"hostname":"stack-0","msg":{"message":"request to http://localhost:4000/api/v1/test failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"}}
`

**Comment by ifokeev** [comment]
> Hi @ifokeev I have an issue during adding my redshift as a source. I described all steps below
> 
> 1. I have Synmetrix deployed
> 2. Sing in with default credentials
> 3. Go to Settings/Data Sources
> 4. Push the Create now
> 5. Choose Redshift
> 6. Fill all fields needed
> 7. Push Test connection and I see two alerts
>    first one: Data Source created
>    second one: [GraphQL] request to http://localhost:4000/api/v1/test failed, reason: socket hang up
> 
> In logs of statefulset stack I see next error: `Driver error: Error: Unexpected CreateOptions.driverFactory result value. Must be either DriverConfig or driver instance: <object>{} at OptsHandler.assertDriverFactoryResult (/app/stack/services/cubejs/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:153:13) at Object.driverFactory (/app/stack/services/cubejs/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:225:21) at processTicksAndRejections (node:internal/process/task_queues:95:5) at default (file:///app/stack/services/cubejs/src/routes/testConnection.js:14:18) {"level":50,"time":1727343743347,"pid":330,"hostname":"stack-0","msg":{"message":"request to http://localhost:4000/api/v1/test failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"}} `

So it's the driver error, we need to fix it on our side or you could provide the PR.

**Comment by OstapW** [comment]
Thank you for your help! It's alive now
